/**
 * Generator: reads src/themes/brand-tokens.ts (the source of truth) and emits
 *
 *   - src/themes/brands.css           (picker site, scoped by [data-brand])
 *   - src/themes/copy-css-snippets.ts (Copy-CSS button strings)
 *   - registry.json                   (root; shadcn GitHub registry endpoint)
 *
 * Run via `bun scripts/build-themes.ts`. The `predev` and `prebuild` npm
 * scripts run it automatically. CI fails the deploy if any emitted file is
 * dirty in git after this runs.
 */
import { writeFile } from "node:fs/promises"

import { BRAND_TOKENS, type BrandTokens } from "../src/themes/brand-tokens"

const GENERATED_BANNER_CSS = `/* GENERATED by scripts/build-themes.ts — do not edit by hand. */
/* Edit src/themes/brand-tokens.ts and run \`bun scripts/build-themes.ts\`. */`

const GENERATED_BANNER_TS = `/**
 * GENERATED by scripts/build-themes.ts — do not edit by hand.
 *
 * Edit src/themes/brand-tokens.ts and run \`bun scripts/build-themes.ts\`.
 */`

/* ------------------------------------------------------------------------- */
/* brands.css                                                                */
/* ------------------------------------------------------------------------- */

function emitVars(vars: Record<string, string>, indent = "  "): string {
  return Object.entries(vars)
    .map(([k, v]) => `${indent}${k}: ${v};`)
    .join("\n")
}

function emitBrandCss(brand: BrandTokens): string {
  const { id, label, cssVars } = brand
  // Theme tokens (radius/font) only need to appear in :root — .dark inherits.
  const lightVars = { ...(cssVars.theme ?? {}), ...cssVars.light }
  const darkVars = cssVars.dark
  const banner = [
    "/* ============================================================== */",
    `/* ${label.padEnd(62)} */`,
    "/* ============================================================== */",
  ].join("\n")
  return [
    banner,
    "",
    `:root[data-brand="${id}"] {`,
    emitVars(lightVars),
    "}",
    "",
    `.dark[data-brand="${id}"] {`,
    emitVars(darkVars),
    "}",
  ].join("\n")
}

function emitBrandsCss(brands: BrandTokens[]): string {
  const head = [
    GENERATED_BANNER_CSS,
    "",
    "/*",
    " * Brand themes — each block scoped by [data-brand] on the <html> element.",
    " * The BrandProvider sets data-brand=\"<id>\". When unset, the shadcn nova",
    " * baseline in index.css applies.",
    " *",
    " * Light vs dark: combine with .dark on the same element, e.g.",
    " *   .dark[data-brand=\"apple\"] { ... }",
    " */",
    "",
  ].join("\n")
  return head + brands.map(emitBrandCss).join("\n\n") + "\n"
}

/* ------------------------------------------------------------------------- */
/* copy-css-snippets.ts                                                      */
/* ------------------------------------------------------------------------- */

function emitCopyCssSnippet(brand: BrandTokens): string {
  const lightVars = { ...(brand.cssVars.theme ?? {}), ...brand.cssVars.light }
  const darkVars = { ...(brand.cssVars.theme ?? {}), ...brand.cssVars.dark }
  return [
    ":root {",
    emitVars(lightVars),
    "}",
    "",
    ".dark {",
    emitVars(darkVars),
    "}",
    "",
  ].join("\n")
}

function emitCopyCssSnippetsTs(brands: BrandTokens[]): string {
  const entries = brands
    .map((b) => `  ${JSON.stringify(b.id)}: ${JSON.stringify(emitCopyCssSnippet(b))},`)
    .join("\n")
  return [
    GENERATED_BANNER_TS,
    "",
    'import type { BrandId } from "@/themes/brand-tokens"',
    "",
    "export const COPY_CSS_SNIPPETS: Record<BrandId, string> = {",
    entries,
    "}",
    "",
  ].join("\n")
}

/* ------------------------------------------------------------------------- */
/* registry.json                                                             */
/* ------------------------------------------------------------------------- */

type RegistryItemCssVars = {
  theme?: Record<string, string>
  light: Record<string, string>
  dark: Record<string, string>
}

type RegistryItem = {
  $schema: string
  name: string
  type: "registry:theme"
  title: string
  description: string
  dependencies?: string[]
  docs?: string
  cssVars: RegistryItemCssVars
}

type Registry = {
  $schema: string
  name: string
  homepage: string
  items: RegistryItem[]
}

function emitRegistryItem(brand: BrandTokens): RegistryItem {
  const item: RegistryItem = {
    $schema: "https://ui.shadcn.com/schema/registry-item.json",
    name: brand.id,
    type: "registry:theme",
    title: brand.label,
    description: brand.description,
    cssVars: {
      light: brand.cssVars.light,
      dark: brand.cssVars.dark,
    },
  }
  if (brand.cssVars.theme && Object.keys(brand.cssVars.theme).length > 0) {
    item.cssVars = { theme: brand.cssVars.theme, ...item.cssVars }
  }
  if (brand.dependencies && brand.dependencies.length > 0) {
    item.dependencies = brand.dependencies
  }
  if (brand.registryDocs) {
    item.docs = brand.registryDocs
  }
  return item
}

function emitRegistry(brands: BrandTokens[]): string {
  const registry: Registry = {
    $schema: "https://ui.shadcn.com/schema/registry.json",
    name: "stylecn",
    homepage: "https://daniakash.github.io/stylecn/",
    items: brands.map(emitRegistryItem),
  }
  return JSON.stringify(registry, null, 2) + "\n"
}

/* ------------------------------------------------------------------------- */
/* main                                                                      */
/* ------------------------------------------------------------------------- */

async function main() {
  await writeFile("src/themes/brands.css", emitBrandsCss(BRAND_TOKENS))
  await writeFile("src/themes/copy-css-snippets.ts", emitCopyCssSnippetsTs(BRAND_TOKENS))
  await writeFile("registry.json", emitRegistry(BRAND_TOKENS))
  console.log(`Wrote brands.css, copy-css-snippets.ts, registry.json (${BRAND_TOKENS.length} brands)`)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
